apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.361.1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: jenkins-jobs
          mountPath: /var/jenkins_jobs
          readOnly: true
        - name: plugins
          mountPath: /usr/share/jenkins/ref/plugins
        - name: plugin-dir
          mountPath: /var/jenkins_plugins
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins
      - name: jenkins-jobs
        emptyDir: {}
      - name: plugins
        emptyDir: {}
      - name: plugin-dir
        emptyDir: {}
